set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE SYSTEM_NAME Linux)
set(CMAKE_CXX_COMPILER /usr/bin/arm-linux-gnueabihf-g++)
set(CMAKE_C_COMPILER /usr/bin/arm-linux-gnueabihf-gcc)
set(CMAKE_FIND_ROOT_PATH /usr/lib/arm-linux-gnueabihf)
