name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    
    runs-on: ubuntu-latest
    container: 
      image: 'Dockerfile'
    steps:
    - uses: actions/checkout@v2
    - name: download deps
      run: ./download_deps.sh
    - name: setup
      run: ./setup_arm.sh
    - name: build
      run: ./build.sh
